name: Swift

on:
  push:
    branches:
      - master/7.0
  pull_request:
    branches:
      - master/7.0

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swiftVersion: [5.6]
    steps:
     - name: Check out  
       uses: actions/checkout@v3
        
     - name: Install Swift
       uses: slashmo/install-swift@v0.1.0
       with:
          version: ${{ matrix.swiftVersion }}
        
     - name: Start Mongo
       run: docker-compose up -d
        
     - name: Run tests
       run: swift test
        
  macos:
    runs-on: macos-12
    steps:
      - name: Install docker
        uses: docker-practice/actions-setup-docker@master
            
      - name: Check out  
        uses: actions/checkout@v3
        
      - name: Start Mongo
        run: docker-compose up -d
          
      - name: Run tests
        run: swift test
