name: Swift

on:
  push:
    branches:
      - master/7.0
  pull_request:
    branches:
      - master/7.0

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        swiftVersion: [5.6]
    steps:
        uses: slashmo/install-swift@v0.1.0
        with:
          version: ${{ matrix.swiftVersion }}
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Setup Mongo
        run: docker-compose up -d
        
      - name: Run tests
        run: swift test
        
  test-macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        mongodb-version: ['4,2', '4.4', '5.0']
    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: mongo-rs
