name: Swift

on:
  push:
    branches:
      - master/7.0
  pull_request:
    branches:
      - master/7.0

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - swift:5.6-focal
          - swiftlang/swift:nightly-main-focal
    container: ${{ matrix.runner }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup Mongo
        run: docker-compose up -d
      - name: Run tests
        run: swift test
