name: Swift

on:
  push:
    branches:
      - master/7.0
  pull_request:
    branches:
      - master/7.0

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        swiftVersion: [5.6]
        os: [ubuntu-20.04, macos-latest]
        
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Swift
        uses: slashmo/install-swift@v0.1.0
        with:
          version: ${{ matrix.swiftVersion }}
          
      - uses: docker-practice/actions-setup-docker@master
        if: matrix.os == 'macos-latest'
        run: set -x
          
      - name: Check out
        uses: actions/checkout@v3
        
      - name: Setup Mongo
        run: docker-compose up -d
      - name: Run tests
        run: swift test
